@EF.Relationship.API_HostAddress = http://localhost:5253

GET http://localhost:5253/Person
Accept: application/json

###

POST http://localhost:5253/Person
Content-Type: application/json

{
    "FirstName": "Sajjad",
    "LastName": "Kheiri",
    "BirthDate": "1998-11-22"
}